"""
Markdown report generator for Setapp rating monitoring.
"""
import os
from datetime import datetime
from . import config


def generate_report(analysis_results: list[dict], snapshot_stats: dict) -> str:
    """
    Generate a comprehensive markdown report from analysis results.

    Args:
        analysis_results: Output from analysis.run_full_analysis()
        snapshot_stats: Dict with keys like total_apps, total_snapshots, run_date
    """
    now = datetime.now()
    lines = []

    # Header
    lines.append("# Setapp App Rating Monitor — Weekly Report")
    lines.append(f"\n**Report generated:** {now.strftime('%Y-%m-%d %H:%M')}")
    lines.append(f"**Analysis window:** Last {config.TREND_WINDOW_DAYS} days")
    lines.append(f"**Total apps tracked:** {snapshot_stats.get('total_apps', 0)}")
    lines.append(f"**Total snapshots in database:** {snapshot_stats.get('total_snapshots', 0)}")

    # Executive summary
    at_risk = [r for r in analysis_results if r["risk"]["is_at_risk"]]
    high_risk = [r for r in at_risk if r["risk"]["risk_level"] == "high"]
    medium_risk = [r for r in at_risk if r["risk"]["risk_level"] == "medium"]

    lines.append("\n---\n")
    lines.append("## Executive Summary")
    lines.append("")
    if at_risk:
        lines.append(
            f"**{len(at_risk)} app(s) flagged as at risk** — "
            f"{len(high_risk)} high severity, {len(medium_risk)} medium severity."
        )
    else:
        lines.append("All apps are within normal rating parameters. No risk flags detected.")

    # At-Risk Apps Section
    if at_risk:
        lines.append("\n---\n")
        lines.append("## Apps At Risk")

        for result in at_risk:
            app = result["app"]
            trend = result["trend"]
            risk = result["risk"]

            severity_icon = {"high": "🔴", "medium": "🟡"}.get(risk["risk_level"], "⚪")
            lines.append(f"\n### {severity_icon} {app['app_name']}")
            lines.append(f"\n**Risk level:** {risk['risk_level'].upper()}")
            lines.append(f"**URL:** [{app['app_url']}]({app['app_url']})")

            if trend["first_rating"] is not None and trend["last_rating"] is not None:
                lines.append(
                    f"\n| Metric | Value |"
                )
                lines.append("| --- | --- |")
                lines.append(f"| Rating (7 days ago) | {trend['first_rating']}% |")
                lines.append(f"| Rating (today) | {trend['last_rating']}% |")
                lines.append(f"| Change | {trend['rating_change']:+.1f} pts ({trend['rating_change_pct']:+.1f}%) |")
                if trend['first_count'] is not None:
                    lines.append(f"| Rating count (start) | {trend['first_count']:,} |")
                if trend['last_count'] is not None:
                    lines.append(f"| Rating count (end) | {trend['last_count']:,} |")
                if trend['count_increase']:
                    lines.append(f"| New ratings | +{trend['count_increase']:,} |")
                lines.append(f"| Trend direction | {trend['trend_direction']} |")

            lines.append("\n**Risk signals:**")
            for reason in risk["risk_reasons"]:
                lines.append(f"- {reason}")

            if result.get("ai_summary"):
                lines.append(f"\n**AI Analysis:**\n")
                lines.append(result["ai_summary"])

    # All Apps Overview
    lines.append("\n---\n")
    lines.append("## All Apps — Rating Overview")
    lines.append("")
    lines.append("| App | Current Rating | 7d Change | Trend | Rating Count | Status |")
    lines.append("| --- | ---: | ---: | :---: | ---: | :---: |")

    for result in analysis_results:
        app = result["app"]
        trend = result["trend"]
        risk = result["risk"]

        current = f"{trend['last_rating']}%" if trend["last_rating"] is not None else "N/A"
        change = f"{trend['rating_change']:+.1f}" if not trend.get("insufficient_data") else "—"
        direction = trend["trend_direction"] if not trend.get("insufficient_data") else "—"
        count = f"{trend['last_count']:,}" if trend.get("last_count") is not None else "N/A"

        status_map = {
            "high": "🔴 HIGH",
            "medium": "🟡 MEDIUM",
            "low": "🟠 LOW",
            "none": "✅ OK",
        }
        status = status_map.get(risk["risk_level"], "✅ OK")

        direction_icon = {"up": "↑", "stable": "→", "down": "↓"}.get(direction, "—")

        lines.append(
            f"| {app['app_name']} | {current} | {change} | {direction_icon} {direction} | {count} | {status} |"
        )

    # Footer
    lines.append("\n---\n")
    lines.append(
        f"*Report generated by Setapp App Rating Monitor on "
        f"{now.strftime('%Y-%m-%d at %H:%M')}.*"
    )

    return "\n".join(lines)


def save_report(content: str, filename: str = None) -> str:
    """Save the report to the reports directory. Returns the file path."""
    if filename is None:
        filename = f"setapp_report_{datetime.now().strftime('%Y-%m-%d')}.md"

    filepath = os.path.join(config.REPORTS_DIR, filename)
    with open(filepath, "w", encoding="utf-8") as f:
        f.write(content)

    return filepath
